[package]
name = "tipping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
petgraph = "0.6.4"
rayon = "1.8.1"
regex = "1.10.3"

[dev-dependencies]
float-cmp = "0.9.0"
